version: "3.8"
services:
  backend:
    image: springreactivedemo
    container_name: spring-reactive-demo
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "7070:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n
